<?php
/**
 * Created by PhpStorm.
 * User: Ilya
 * Date: 15.04.2017
 * Time: 1:05
 */

class Model_item extends Model
{
    function get_data($parameters)
    {
        require_once 'application/libs/config.php';
        require_once 'application/libs/Template.php';

//        global $db_host, $db_name, $db_user, $db_pass, $table_items, $table_cats, $site_title;

        $p_id = abs(intval($parameters[0]));
        $conn = mysqli_connect($db_host, $db_user, $db_pass, $db_name);
        $result = mysqli_query($conn, "SELECT * FROM $table_items i JOIN $table_cats c ON c.cat_id = i.cat_id WHERE i.id = $p_id LIMIT 1");

//        if (!($result->num_rows == 1))
//        {
//            throw_error("Нет такой новости.");
//        }

        $row = mysqli_fetch_array($result);

        mysqli_close($conn);

        $data = array();
        $data[0] = $row;
        $data[1] = $site_title;
        return $data;
//        parent::get_data(); // TODO: Change the autogenerated stub
    }
}